name: Deploy to Production
on:
  workflow_run:
    workflows: [Linting]
    types:
      - completed
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Executing SSH Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.DIR }}
            nvm use 22
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            php artisan optimize:clear
            git pull origin main
            composer2 install
            npm install
            npm run build
            php artisan optimize
