name: Deploy to Production
on:
  workflow_run:
    workflows: [Linting]
    types:
      - completed
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Executing SSH Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.DIR }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            php artisan optimize:clear
            git pull origin dev
            composer2 install
            php artisan migrate:fresh --seed --force
            npm install
            npm run build
            php artisan optimize
